import React from "react"
import Head from "next/head"
import Header from "../header"
import classes from './Layout.module.scss';

type LayoutProps = {
  children?: React.ReactNode
}

const Layout = ({ children }: LayoutProps) => (
  <>
    <Head>
      <title>Urban Booker</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
      <section className={classes.container}>
        <Header />
        {children}
      </section>
  </>
)

export default Layout

